# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='created_tiem',
            new_name='created_time',
        ),
    ]
